apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJ1bHVrYmVrMjQ6Z2hwX2FSQXFHVHpyOGtYbWVzQ1A1aElyeVJsNzZvOTlnSTJESlRJdyIKICAgIH0sCiAgICAiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjoge30sCiAgICAiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvYWNjZXNzLXRva2VuIjoge30sCiAgICAiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvcmVmcmVzaC10b2tlbiI6IHt9CiAgfSwKICAiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKICAiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIKfQ==
type: kubernetes.io/dockerconfigjson
